### ISSUE TITLE
save/load input names

### ISSUE THREAD

**Issue by miaket** [guiconti/NEAT_builder#25]
opa

**Comment by mmakarios** [comment]
I think the best approach is to have all the data in the store, and apply it to the localstorage on store updates (Redux has a store.subscribe method). And on the app first load, populate the store using the localstorage.

**Comment by mmakarios** [comment]
Example in Redux by its creator: https://egghead.io/lessons/javascript-redux-persisting-the-state-to-the-local-storage

**Comment by miaket** [comment]
Hum, nice. That makes sense. I did notice some unnecessary amount of local storage accesses. 
I'll check that out later, thank you!

**Comment by miaket** [comment]
que caraio

**Comment by guiconti** [comment]
Can you please fix the inputs? You have until tomorrow or you will be fired. Best regards

**Comment by miaket** [comment]
asejpeo

**Comment by miaket** [comment]
fixed

**Comment by miaket** [comment]
ABRI CALMa
