### ISSUE TITLE
Fix text typo in Flappy's pipe description

### ISSUE THREAD

**Issue by miaket** [guiconti/NEAT_builder#8]
Pipes variables:
...
pipes.closest.top (**Closes** pipe top entrance)
...

**Comment by miaket** [comment]
vai fazê ou nao, caraljo

**Comment by lucasl2** [comment]
On it

**Comment by miaket** [comment]
Did you finish it already? Can we close it?

**Comment by miaket** [comment]
Arent the instructions comming from the db? I think you should take a look there to make sure its fixed.
My guess is that we are not actually using this piece of code you changed. (We should delete it if its the case)

**Comment by miaket** [comment]
responde o cacalho parece que to falando com uma parede filho daupta
